import { Inter } from "next/font/google";
import "./globals.css";
import "../StylesImport";
import Header from "@/layouts/Header/Header";
import Footer from "@/layouts/Footer/Footer";
import CookieModal from "@/modals/CookieModal/CookieModal";
// import ScrollToTop from "@/services/ScrollToTop";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        {/* <ScrollToTop /> */}
        <CookieModal />
      </body>
    </html>
  );
}
